### ISSUE TITLE
How to get MAC address of device

### ISSUE THREAD

**Issue by atulord** [jorisvandesande/unifi-api-client#2]
Hi,
I do apologise as I know this is an inappropriate manner of using thee issue feature of Github, but I am currently working on a project that involves creating a custom portal for a unifi ap. We are using a node server and an angular front end. I wanted to know how we can get the users mac address in order to approve them to utilise the network. Currently we see no way of fetching the MAC address and want to know if you have any suggestions about it

**Comment by jorisvandesande** [comment]
You can monitor the requests that the Unifi dashboard uses to fetch the "clients" information, via your browsers' developers tools. All the url's that are called via the dashboard can be called via this API client too.

The URL that is called to fetch the clients is: `/api/s/default/stat/sta` . You can use this PHP client to fetch the clients and find the mac address that belongs to the IP address of the currently connected user (`$_SERVER['SERVER_ADDR']` in PHP).

**Comment by malle-pietje** [comment]
@ChukaEbi late reply since I only just read you issue here. What is suggested by @jorisvandesande will work when the controller and client are on the same subnet. If you have a controller that isn't, my suggestion is to have a good look at the index.html file on the controller in the site's portal directory and customise it, after making a backup copy of course This folder becomes available after you have enabled portal customisation in your controller settings for the site. Using javascript to redirect the client to a specific url you can add in GET parameters to the url by use of the special <unifi> tags. The client MAC address is available with one these tags.
